name: workflow

on:
  pull_request:
  release:
  push:

jobs:
  plan:
    name: Plan
    runs-on: ubuntu-latest
    outputs:
      exitcode: ${{ steps.plan.outputs.exitcode }}
    steps:
      - name: Plan
        id: plan
        run: |
          if $(exit 1); then
            echo "exitcode=0" >> $GITHUB_OUTPUT
          else
            echo "exitcode=1" >> $GITHUB_OUTPUT
          fi

  test:
    name: Test
    runs-on: ubuntu-latest
    needs: [ plan ]
    steps:
      - run: echo ${{ needs.plan.outputs.exitcode }}
